# Generated by Django 4.1.7 on 2023-04-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_personas_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='age',
        ),
    ]
