# Generated by Django 4.1.7 on 2023-04-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_personas_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
