# Generated by Django 4.1.7 on 2023-04-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_personas_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
