# Generated by Django 4.1.7 on 2023-03-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=250)),
                ('apellido', models.TextField(max_length=250)),
                ('edad', models.IntegerField(max_length=3)),
            ],
        ),
    ]
