# Generated by Django 4.1.7 on 2023-04-05 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_modelo_edad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modelo',
        ),
    ]
